//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerAccount
    {
        public short userID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string first_NM { get; set; }
        public string last_NM { get; set; }
        public string email { get; set; }
    }
}
